name: Comprovació Markdown

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  markdownlint:
    name: Revisar fitxers Markdown
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositori
        uses: actions/checkout@v4

      - name: Comprovar estil dels fitxers Markdown
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: '**/*.md'